#!/bin/bash
#===============================================================================
#
#          FILE: psql2md
# 
#         USAGE: psql --no-psqlrc -qtc SELECT 530 "count", 0.963636363633636" | ./psql2md 
# 
#   DESCRIPTION: pull table output from psql over stdin and convert it to markdown
# 
#         NOTES: 
#  count |        ?column?        
# -------+------------------------
#   530 | 0.96363636363636363636
# (1 row)
#
# becomes
# | count | ?column?              |
# |-------|-----------------------|
# | 530   | 0.96363636363636363636|
# (1 row)
#
#        AUTHOR: Kirk Roybal (), kirk@webfinish.com
#  ORGANIZATION: 
#       CREATED: 02/02/2018 10:46
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

cat - | 
    sed '/^[[:space:]]*$/d' | # remove blank lines
    sed '1s/^[[:space:]]*//g' | # trim leading space on first line
    sed '1s/[[:space:]]*|[[:space:]]*/|/g' | #replace the spaces in the header line
    sed '1s/|/** | **/g' | # bold the header line
    sed -e '1s/^/ **/' -e '1s/$/** /' | # begin/end bold
    sed -e 's/^/|/g'   -e 's/$/|/g'| # add leading/trailing pipes
    sed '2s/+/|/g' | #convert plus to pipe on 2nd line
    sed '$s/^.*(\(.*\) \(row.*\)).*$/|(\1 \2) |/' # change (x row(s)) to | (x row(s)) |
