#!/bin/bash
#===============================================================================
#
#          FILE: psql2md.bash
#
#         USAGE: ./psql2md.bash
#
#   DESCRIPTION:  Convert pipe delimited psql output to markdown table
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Kirk L. Roybal (DBRE), kirk@webfinish.com
#  ORGANIZATION: Private
#       CREATED: 04/20/2021 22:40:49
#      REVISION:  ---
#===============================================================================



ScriptVersion="1.0"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
	cat <<- EOT

  Usage :  ${0##/*/} [options] [--] 

  Options: 
  -f|file [name]  Input file Default: STDIN
  -h|help         Display this message
  -v|version      Display script version

	EOT
}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------
input='-'
while getopts ":f:hv" opt
do
  case $opt in

    f|file     ) intput="$OPTARG";;

    h|help     )  usage; exit 0   ;;

    v|version  )  echo "$0 -- Version $ScriptVersion"; exit 0   ;;

    \? )  echo -e "\n  Option does not exist : $OPTARG\n"
          usage; exit 1   ;;

  esac    # --- end of case ---
done
shift $(($OPTIND-1))

cat "$input" | 
    sed '/^[[:space:]]*$/d' | # remove blank lines
    sed '1s/^[[:space:]]*//g' | # trim leading space on first line
    sed '1s/[[:space:]]*|[[:space:]]*/|/g' | #replace the spaces in the header line
    sed '1s/|/** | **/g' | # bold the header line
    sed -e '1s/^/ **/' -e '1s/$/** /' | # begin/end bold
    sed -e 's/^/|/g'   -e 's/$/|/g'| # add leading/trailing pipes
    sed '2s/+/|/g' | #convert plus to pipe on 2nd line
    sed '$s/^.*(\(.*\) \(row.*\)).*$/|(\1 \2) |/' # change (x row(s)) to | (x row(s)) |
