#!/bin/bash
#===============================================================================
#
#          FILE: urlencode
#
#         USAGE: ./urlencode
#
#   DESCRIPTION: Translate a file or stdin to URL encoding with nothing but sed 
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Kirk L. Roybal (DBRE), iirk.roybal@gmail.com
#       CREATED: 05/06/2021 12:51:08 PM
#      REVISION:  ---
#       LICENSE: PostgreSQL
#===============================================================================
set -eo pipefail

replacements='s:%:%25:g
s: :%20:g
s:<:%3C:g
s:>:%3E:g
s:#:%23:g
s:{:%7B:g
s:}:%7D:g
s:|:%7C:g
s:\\:%5C:g
s:\^:%5E:g
s:~:%7E:g
s:\[:%5B:g
s:\]:%5D:g
s:`:%60:g
s:;:%3B:g
s:/:%2F:g
s:?:%3F:g
s^:^%3A^g
s:@:%40:g
s:=:%3D:g
s:&:%26:g
s:\$:%24:g
s:\!:%21:g
s:\*:%2A:g'

cat "${1:--}" | sed -f <((echo "$replacements"))
